### ISSUE TITLE
Failed:     Stancl\JobPipeline\JobPipeline

### ISSUE THREAD

**Issue by abdelrauof97** [archtechx/jobpipeline#6]
i use /tenancy-for-laravel/saas-boilerplate but when i do run "php artisan queue:work" and make a registration. the We're building your site page freezes and an error comes at the terminal saying "Failed:     Stancl\JobPipeline\JobPipeline" 
what is the issue?

**Comment by ismaelfi** [comment]
Hi, 

Do you have [phpredis](https://github.com/phpredis/phpredis/blob/develop/INSTALL.markdown) or [predis ](https://github.com/predis/predis)  properly configured in your machine ?
