### ISSUE TITLE
[bug] Jobs failing silently

### ISSUE THREAD

**Issue by hackeresq** [archtechx/jobpipeline#8]
I have been using this package with Stancl\Tenancy for ~1.5 years.  It's used as intended in the TenancyServiceProvider to listen for the TenantCreated event and do various onboarding activities.  In my case, in addition to creating the database, migrating, and seeding, I have additional jobs for creating a Cashier subscription, creating a Password Grant Client, creating a record for the tenant's domain, and then finally switching the tenant to "ready" (per the Subscriber-only content).

90% of the time, these jobs run perfectly and the tenant is set to "ready." 10% of the time, all of the jobs complete successfully, the Stripe subscription is created, the Passport client is created, the domains are created, except the last job **and the tenant is not switched to "ready."**

I was able to increase the 90% success rate recently by switching to 2 separate pipelines. Specifically, I separated out the Stripe subscription creation (which makes an HTTP request). I speculated that HTTP request may be slow sometimes so it causes issues. This gives me a better success rate:

```PHP
            Events\TenantCreated::class => [
                // First listener
                JobPipeline::make([
                    Jobs\CreateDatabase::class,
                    Jobs\MigrateDatabase::class,   
                    Onboarding\CreatePasswordGrantClientJob::class,
                    Onboarding\SetDefaultSettingsJob::class,
                    Onboarding\InsertFallbackDomainEntryJob::class,
                    Jobs\SeedDatabase::class,
                    Onboarding\FinishOnboardingJob::class
                ])->send(function (Events\TenantCreated $event) {
                    return $event->tenant;
                })->shouldBeQueued(true),

                // Second listener 
                JobPipeline::make([
                    Onboarding\CreateStripeCustomerJob::class
                ])->send(function (Events\TenantCreated $event) {
                    return $event->tenant;
                })->shouldBeQueued(true),
            ],
```

But I still have failures. Silently. I've tried capturing errors by adding a `failed()` method to my jobs, but I never get errors:

```PHP
    public function failed(Throwable $exception)
    {
        $this->tenant->setAttribute('error', $exception->getMessage());
        $this->tenant->save();

        // Send user notification of failure, etc...
    }

```

Notable that I use Laravel Vapor. This issue does not occur locally. Only on Vapor. And there are no errors in the Queue or CLI logs when I get failed tenants. 

Here's what a typical job looks like:

```PHP
class FinishOnboardingJob implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    /** 
     * @var TenantWithDatabase 
     */
    protected $tenant;

    /**
     * Create a new job instance.
     *
     * @return void
     */
    public function __construct(TenantWithDatabase $tenant)
    {
        $this->tenant = $tenant;
    }

    /**
     * Execute the job.
     *
     * @return void
     */
    public function handle()
    {

        $this->tenant->run(function ($tenant) {

            $tenant->update([
                'error' => null,
                'ready' => true,
                'request' => [],
            ]);
        });

        // $this->tenant->setAttribute('request', null);
        // $this->tenant->setAttribute('ready', true);
        // $this->tenant->save();
    }

```

Have you experienced this? Any suggested debugging you can share?

**Comment by stancl** [comment]
> Silently. I've tried capturing errors by adding a failed() method to my jobs, but I never get errors

I think Laravel's native exception handling for jobs won't work well here because the *real* job is the JobPipeline, as the outer wrapper. With the individual jobs being executed inside the pipeline.

It's also hard to see the actual error from jobs inside the pipeline when running `queue:work`. You just see that the pipeline failed.

You probably want to add some logic to the JobPipeline to catch exceptions and report them in some specific way? Happy to take a look at anything you come up with that we could add to the package
